version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: homemed_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: homemed_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # <-- Lê o SQL automaticamente
volumes:
  pgdata: